FROM python:3.10.8

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

# Use this command to run Streamlit
CMD ["streamlit", "run", "--server.port=8501", "--server.address=0.0.0.0", "meal_recommender.py"]